name: SimpleServerTransfer
version: '${project.version}'
main: dev.professionalflare.sst.SimpleServerTransfer
api-version: '1.20.6'
author: ProfessionalFlare
description: Transfers players to another server using the vanilla Transfer packet.
softdepend:
  - Geyser-Spigot
  - floodgate